import { useState, useMemo } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { getSections, updateSection, getTerms, getUsers, getEnrollments } from '../../api';
import PageHeader from '../../components/PageHeader';
import Modal from '../../components/Modal';
import EmptyState from '../../components/EmptyState';
import DataTable, { type DataTableHeader } from '../../components/DataTable';
import TableSkeleton from '../../components/TableSkeleton';
import SearchInput from '../../components/SearchInput';
import Chip from '../../components/Chip';
import Icon from '../../components/Icon';
import { useToast } from '../../components/Toast';
import { InputField, SelectField } from '../../components/FormField';
import { parseApiError } from '../../lib/apiError';

const HEADERS: DataTableHeader[] = [
  { label: 'Block' }, { label: 'Course' }, { label: 'Term' }, { label: 'Faculty' },
  { label: 'Schedule' }, { label: 'Room' }, { label: 'Enrolled', align: 'center' },
  { label: '', align: 'right' },
];

// Day-of-week parser + builder — keeps the storage format ('MWF', 'TTh') aligned
// with the per-day chip UI.
const DAY_ORDER = ['M', 'T', 'W', 'Th', 'F', 'Sat'] as const;
const DAY_LABEL: Record<string, string> = { M: 'Mon', T: 'Tue', W: 'Wed', Th: 'Thu', F: 'Fri', Sat: 'Sat' };

function parseDays(s: string | null | undefined): string[] {
  if (!s) return [];
  let rest = s.replace(/\s+/g, '');
  const out = new Set<string>();
  while (/sat/i.test(rest)) { out.add('Sat'); rest = rest.replace(/sat/i, ''); }
  while (/th/i.test(rest))  { out.add('Th');  rest = rest.replace(/th/i,  ''); }
  for (const c of rest.toUpperCase()) {
    if ('MTWF'.includes(c)) out.add(c);
  }
  return [...out];
}

function joinDays(days: string[]): string {
  return DAY_ORDER.filter(d => days.includes(d)).join('');
}

export default function Sections() {
  const qc = useQueryClient();
  const toast = useToast();
  const { data: sections = [], isLoading } = useQuery({ queryKey: ['sections'], queryFn: () => getSections() });
  const { data: terms = [] }       = useQuery({ queryKey: ['terms'],       queryFn: () => getTerms() });
  const { data: faculty = [] }     = useQuery({ queryKey: ['users', 'faculty'], queryFn: () => getUsers('faculty') });
  const { data: enrollments = [] } = useQuery({ queryKey: ['enrollments'], queryFn: () => getEnrollments() });

  const [editing, setEditing] = useState<any | null>(null);
  const [editForm, setEditForm] = useState({ facultyId: '', dayOfWeek: '', startTime: '', endTime: '', room: '' });
  const [err, setErr] = useState('');
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const resetErr = () => { setErr(''); setFieldErrors({}); };

  const [query, setQuery] = useState('');
  const [termFilter, setTermFilter] = useState<string>('active');
  const [tbaOnly, setTbaOnly] = useState(false);

  const updateMut = useMutation({
    mutationFn: () => updateSection(editing.id, {
      facultyId: editForm.facultyId || null,
      dayOfWeek: editForm.dayOfWeek || null,
      startTime: editForm.startTime || null,
      endTime:   editForm.endTime   || null,
      room:      editForm.room      || null,
    }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['sections'] });
      setEditing(null); resetErr();
      toast.push({ tone: 'success', title: 'Section updated' });
    },
    onError: (e: unknown) => { const p = parseApiError(e, 'Failed to update section'); setErr(p.message); setFieldErrors(p.fields); },
  });

  const activeTerm = terms.find((t: any) => t.is_active === true || t.is_active === 'true');
  const enrolledFor = (sectionId: string) =>
    enrollments.filter((e: any) => e.section_id === sectionId && e.status === 'enrolled').length;

  const filtered = useMemo(() => sections.filter((s: any) => {
    if (termFilter === 'active') {
      if (s.term_name !== activeTerm?.name) return false;
    } else if (termFilter !== 'all') {
      if (s.term_name !== termFilter) return false;
    }
    if (tbaOnly && s.faculty_id) return false;
    if (query) {
      const q = query.toLowerCase();
      if (!`${s.section_code} ${s.course_code} ${s.course_title} ${s.block_label || ''}`.toLowerCase().includes(q)) return false;
    }
    return true;
  }), [sections, termFilter, query, tbaOnly, activeTerm]);

  const tbaCount = sections.filter((s: any) => !s.faculty_id).length;

  return (
    <div>
      <PageHeader
        eyebrow="Scheduling"
        title="Sections"
        subtitle="Auto-generated by 'Open term' from each block's curriculum. Use this page to assign faculty + schedule + room to TBA sections."
      />

      <div className="bg-beige-100 border border-khaki-200 rounded-lg px-3 py-2 mb-4 text-xs text-stone-600 flex items-start gap-2">
        <Icon name="info" size={14} className="mt-0.5 text-stone-400 flex-shrink-0" />
        <span>Sections are created automatically when an admin opens a term. To add new sections, go to <strong>Terms</strong> and click "Open term" on the active term.</span>
      </div>

      <div className="flex items-center gap-3 mb-4 flex-wrap">
        <SearchInput value={query} onChange={setQuery} placeholder="Search section, block, or course…" className="w-80" />
        <div className="flex items-center gap-1.5 flex-wrap">
          <Chip active={termFilter === 'active'} onClick={() => setTermFilter('active')}>This term</Chip>
          <Chip active={termFilter === 'all'} onClick={() => setTermFilter('all')}>All terms</Chip>
          {terms.filter((t: any) => t.name !== activeTerm?.name).map((t: any) => (
            <Chip key={t.id} active={termFilter === t.name} onClick={() => setTermFilter(t.name)}>{t.name}</Chip>
          ))}
        </div>
        <Chip active={tbaOnly} onClick={() => setTbaOnly(v => !v)}>
          <Icon name="alert-triangle" size={10} className="text-amber-500" /> TBA only ({tbaCount})
        </Chip>
        <span className="text-xs text-stone-400 ml-auto tabular">{filtered.length} sections</span>
      </div>

      {isLoading ? (
        <TableSkeleton headers={HEADERS} rows={6} />
      ) : filtered.length === 0 ? (
        <div className="card p-0"><EmptyState icon="school" title="No sections" message="Open a term from the Terms page to generate sections from the curriculum." /></div>
      ) : (
        <DataTable headers={HEADERS}>
          {filtered.map((s: any) => {
            const enrolled = enrolledFor(s.id);
            const fillPct  = s.capacity ? (enrolled / s.capacity) * 100 : 0;
            const tba = !s.faculty_id;
            return (
              <tr key={s.id} className="hover:bg-beige-50 transition-colors">
                <td className="table-td">
                  <span className="font-mono text-xs font-semibold text-olive-600 bg-beige-100 px-2 py-0.5 rounded">{s.block_label}</span>
                </td>
                <td className="table-td">
                  <span className="font-mono text-xs text-stone-500 font-semibold">{s.course_code}</span>
                  <span className="ml-2">{s.course_title}</span>
                </td>
                <td className="table-td text-stone-500 text-xs">{s.term_name}</td>
                <td className="table-td text-xs">
                  {s.faculty_name
                    ? <span className="text-stone-700">{s.faculty_name}</span>
                    : <span className="badge badge-amber"><Icon name="alert-triangle" size={10} /> TBA</span>}
                </td>
                <td className="table-td text-xs">
                  {s.day_of_week
                    ? <><span className="font-mono">{s.day_of_week}</span> {s.start_time?.slice(0, 5)}–{s.end_time?.slice(0, 5)}</>
                    : <span className="text-stone-300">—</span>}
                </td>
                <td className="table-td text-stone-500 text-xs">{s.room ?? <span className="text-stone-300">—</span>}</td>
                <td className="table-td">
                  <div className="flex items-center gap-2 justify-center">
                    <span className="tabular text-xs font-semibold text-stone-700 w-12 text-right">{enrolled}/{s.capacity}</span>
                    <div className="w-16 h-1.5 bg-beige-200 rounded-full overflow-hidden">
                      <div
                        className={`h-full rounded-full ${fillPct >= 90 ? 'bg-red-400' : fillPct >= 70 ? 'bg-khaki-400' : 'bg-olive-300'}`}
                        style={{ width: `${Math.min(100, fillPct)}%` }}
                      />
                    </div>
                  </div>
                </td>
                <td className="table-td text-right">
                  <button className={`btn-icon ml-auto ${tba ? 'text-amber-600' : ''}`}
                    title={tba ? 'Assign faculty + schedule' : 'Edit'}
                    onClick={() => {
                      setEditing(s);
                      setEditForm({
                        facultyId: s.faculty_id ?? '',
                        dayOfWeek: s.day_of_week ?? '',
                        startTime: (s.start_time ?? '').slice(0, 5),
                        endTime:   (s.end_time   ?? '').slice(0, 5),
                        room:      s.room ?? '',
                      });
                      resetErr();
                    }}>
                    <Icon name="pencil" size={13} />
                  </button>
                </td>
              </tr>
            );
          })}
        </DataTable>
      )}

      {editing && (
        <Modal title={editing.block_label + ' · ' + editing.course_code}
          subtitle={editing.course_title}
          onClose={() => { setEditing(null); resetErr(); }} size="lg">
          <div className="space-y-3">
            <SelectField label="Faculty" value={editForm.facultyId}
              onChange={e => setEditForm(f => ({ ...f, facultyId: e.target.value }))} error={fieldErrors.facultyId}>
              <option value="">— TBA —</option>
              {faculty.map((f: any) => <option key={f.id} value={f.id}>{f.full_name}</option>)}
            </SelectField>
            <div>
              <label className="label">Day(s)</label>
              <div className="flex gap-1.5 flex-wrap">
                {DAY_ORDER.map(d => {
                  const selected = parseDays(editForm.dayOfWeek);
                  const active = selected.includes(d);
                  return (
                    <button key={d} type="button"
                      className={`chip ${active ? 'active' : ''}`}
                      onClick={() => {
                        const next = active ? selected.filter(x => x !== d) : [...selected, d];
                        setEditForm(f => ({ ...f, dayOfWeek: joinDays(next) }));
                      }}>
                      {DAY_LABEL[d]}
                    </button>
                  );
                })}
              </div>
              {fieldErrors.dayOfWeek && <p className="text-xs text-red-600 mt-1">{fieldErrors.dayOfWeek}</p>}
            </div>
            <div className="grid grid-cols-3 gap-3">
              <InputField label="Start time" type="time" value={editForm.startTime}
                onChange={e => setEditForm(f => ({ ...f, startTime: e.target.value }))} error={fieldErrors.startTime} />
              <InputField label="End time" type="time" value={editForm.endTime}
                onChange={e => setEditForm(f => ({ ...f, endTime: e.target.value }))} error={fieldErrors.endTime} />
              <InputField label="Room" value={editForm.room}
                onChange={e => setEditForm(f => ({ ...f, room: e.target.value }))}
                placeholder="Room 201" error={fieldErrors.room} />
            </div>
            {err && <p className="text-red-600 text-sm bg-red-50 border border-red-200 rounded-lg px-3 py-2">{err}</p>}
            <div className="flex justify-end gap-2 pt-1">
              <button className="btn-ghost" onClick={() => { setEditing(null); resetErr(); }}>Cancel</button>
              <button className="btn-primary" onClick={() => { resetErr(); updateMut.mutate(); }} disabled={updateMut.isPending}>
                {updateMut.isPending ? 'Saving…' : 'Save changes'}
              </button>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
}
